"""SQL queries for cost data retrieval."""

COST_DATA_QUERY = """
SELECT 
    CR.FISCAL_YEAR_MONTH_NO,
    PE.LEAD_DISTRICT_ID,
    PE.LEAD_DISTRICT,
    CR.PROJECT_NUMBER,
    WBS.CBS_HIERARCHY,
    CR.WBS_ELEMENT,
    WBS.WBS_DESCRIPTION,
    WBS.ACCOUNT_CODE,
    WBS.UNIT_OF_MEASURE_ID,
    
    CURRENT_ESTIMATE_QUANTITY AS CE_QTY,
    CURRENT_BUDGET_QUANTITY AS CB_QTY,
    CURRENT_BUDGET_MHF AS CB_MHF,
    CURRENT_BUDGET_AMOUNT AS CB_AMT,
    CURRENT_BUDGET_UNIT_COST AS CB_UNIT_COST,
    
    QUANTITY AS PER_QTY,
    PERCENT_COMPLETE AS PER_PERC_COMP,
    MANHOURS AS PER_MH,
    MHF AS PER_MHF,
    MH_G_PER_L AS PER_MH_GL,
    UOM_PER_MH AS PER_UOM_MH,
    PF AS PER_PF,
    CF AS PER_CF,
    LEI AS PER_LEI,
    ACTUAL_COST AS PER_SPEND,
    UNIT_COST AS PER_UNIT_COST,
    ACTUAL_COST_G_PER_L,
    
    JTD_QUANTITY AS JTD_QTY,
    JTD_PERCENT_COMPLETE AS JTD_PERC_COMP,
    JTD_MANHOURS AS JTD_MH,
    JTD_MHF AS JTD_MHF,
    JTD_MH_G_PER_L AS JTD_MH_GL,
    JTD_UOM_PER_MH AS JTD_UOM_MH,
    JTD_PF AS JTD_PF,
    JTD_CF AS JTD_CF,
    JTD_LEI,
    JTD_ACTUAL_COST AS JTD_SPEND,
    JTD_UNIT_COST AS JTD_UNIT_COST,
    JTD_COST_G_PER_L,
    
    FORECAST_REMAINING_QUANTITY,
    WBS.HD_FORECAST_METHOD,
    FORECAST_REMAINING_MHF,
    FORECAST_MHF,
    FORECAST_REMAINING_MH,
    FORECAST_MH,
    FORECAST_MH_G_PER_L,
    FORECAST_REMAINING_PF,
    FORECAST_PF,
    FORECAST_REMAINING_CF,
    FORECAST_CF,
    FORECAST_REMAINING_LEI,
    FORECAST_LEI,
    FORECAST_REMAINING_UNIT_COST,
    FORECAST_UNIT_COST,
    FORECAST_REMAINING_AMOUNT,
    FORECAST_AMOUNT,
    FORECAST_AMOUNT_G_PER_L,
    FORECAST_CHANGE,
    (JTD_ACTUAL_COST / NULLIFZERO(JTD_PERCENT_COMPLETE)) - FORECAST_AMOUNT AS SL_VARIANCE

FROM PROD_ENT_CONSUMPTION.SEM_VW.CR_CUBE_DATA_WBS CR
LEFT JOIN PROD_ENT_CONSUMPTION.SEM_VW.WBS_SNAPSHOT WBS
    ON CR.WBS_ELEMENT = WBS.WBS_ELEMENT
    AND CR.FISCAL_YEAR_MONTH_NO = WBS.FISCAL_YEAR_MONTH_NO
LEFT JOIN PROD_KDS_CONSUMPTION.SEM.PROJECT_EXPLORER_KDS PE
    ON CR.PROJECT_NUMBER = PE.PROJECT_NUMBER
WHERE CR.PROJECT_NUMBER IN ({project_numbers})
AND CR.FISCAL_YEAR_MONTH_NO >= %(start_month)s
ORDER BY CR.FISCAL_YEAR_MONTH_NO, CBS_HIERARCHY ASC
"""

DISTRICTS_QUERY = """
SELECT DISTINCT
    LEAD_DISTRICT,
    LEAD_DISTRICT_ID
FROM PROD_KDS_CONSUMPTION.SEM.PROJECT_EXPLORER_KDS
ORDER BY LEAD_DISTRICT
"""

PROJECTS_QUERY = """
SELECT DISTINCT
    PROJECT_NUMBER,
    PE.LEAD_DISTRICT_ID,
    PE.LEAD_DISTRICT
FROM PROD_KDS_CONSUMPTION.SEM.PROJECT_EXPLORER_KDS PE
WHERE LEAD_DISTRICT_ID = %(district_id)s
ORDER BY PROJECT_NUMBER
"""

